sudo: required
services:
- docker
language: bash
script:
# build image
- docker build -t spanghf37/homebridge-knx .
# test image
- docker run spanghf37/homebridge-knx uname -a
# push image
- >
  #if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
    TAG=$(grep "FROM " Dockerfile | sed 's/.*://')
    docker tag spanghf37/homebridge-knx spanghf37/homebridge-knx:$TAG
    docker tag spanghf37/homebridge-knx spanghf37/homebridge-knx:amd64
    docker push spanghf37/homebridge-knx:$TAG
    docker push spanghf37/homebridge-knx:amd64
  #fi
