sudo: required
services:
- docker
language: bash
script:
# prepare qemu
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
# get qemu-arm-static binary
- mkdir tmp
- >
  pushd tmp &&
  curl -L -o qemu-arm-static.tar.gz https://github.com/multiarch/qemu-user-static/releases/download/v2.6.0/qemu-arm-static.tar.gz &&
  tar xzf qemu-arm-static.tar.gz &&
  popd
# build image
- docker build -t spanghf37/homebridge-knx .
# test image
- docker run spanghf37/homebridge-knx uname -a
# push image
- >
  if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
    TAG=$(grep "FROM " Dockerfile | sed 's/.*://')
    docker tag spanghf37/homebridge-knx spanghf37/homebridge-knx:$TAG
    docker tag spanghf37/homebridge-knx spanghf37/homebridge-knx:latest
    docker push spanghf37/homebridge-knx:$TAG
    docker push spanghf37/homebridge-knx:latest
  fi
